### ISSUE TITLE
Test Case 1

### ISSUE THREAD

**Issue by Zayne168** [Zayne168/Project_4#1]
Test-Case-01: Test that there is a valid API web key.  module_3/aioutput.py lines 13-17. function defined in unitTesting line 2

**Comment by Zayne168** [comment]
Implemented test case 1.

**Comment by Zayne168** [comment]
moved in aioutput.py to lines 11-22

**Comment by jthomasw** [comment]
test case works, moved in aioutput.py to lines 19-23
