### ISSUE TITLE
Test Case 4

### ISSUE THREAD

**Issue by Zayne168** [Zayne168/Project_4#4]
Test Case 4:     module_3/unitTesting line 24; implemented line module_3/aioutput.py lines 34-35 currently. Tests that each summary made by the AI is actually 50 words or under. If not, a message gets printing alerting the user, but no action is taken.

**Comment by jthomasw** [comment]
Test completed. implemented on lines 79 -84 in unitTesting.py. Called on lines 38 - 39 of aioutput.py.
